apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kv-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"   # We will not use pod identity for this example. We will use SP
    keyvaultName: "myKV-blah-blah-blah"   # This is the name of KeyVault resource that we created in previous step
    cloudName: "AzurePublicCloud"   
    objects:  |
      array:
        - |
          objectName: db-username
          objectType: secret      # object types: secret, key or cert
          objectVersion: "" 
        - |
          objectName: db-password
          objectType: secret   
          objectVersion: ""       
    resourceGroup: "teamResources"    # Resource goup that you have used to create KeyVault
    subscriptionId: "350001cf-c856-4815-8923-cfda12c7da53"       
    tenantId: "871926aa-0cd1-4a7f-aa2c-64060253914f"   