apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  labels:
    deploy: poi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryylw2763.azurecr.io/tripinsights/poi:latest
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: prod-db-secret


---
apiVersion: v1
kind: Service
metadata: 
  name: poi
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: poi
