apiVersion: v1
kind: Service
metadata: 
  name: tripviewerservice
  labels:
    run: trip-viewer
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: trip-viewer
