apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips-deployment
  labels:
    deploy: trips
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registryylw2763.azurecr.io/tripinsights/trips:latest
        ports:
        - containerPort: 80
