apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-profile-deployment
  labels:
    deploy: user-profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-profile
  template:
    metadata:
      labels:
        app: user-profile
    spec:
      containers:
      - name: user-profile
        image: registryylw2763.azurecr.io/tripinsights/userprofile:latest
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: prod-db-secret
---
apiVersion: v1
kind: Service
metadata: 
  name: user-profile-service
  labels:
    run: user-profile
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: user-profile

