apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java-deployment
  labels:
    deploy: user-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registryylw2763.azurecr.io/tripinsights/user-java:latest
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: prod-db-secret

---
apiVersion: v1
kind: Service
metadata: 
  name: user-java-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: user-java

