apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  namespace: api
  labels:
    deploy: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
          - name: poi
            image: registryylw2763.azurecr.io/tripinsights/poi:latest
            ports:
            - containerPort: 80
            volumeMounts:
            - name: secrets-store-inline
              mountPath: "/secrets"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname"
            nodePublishSecretRef: 
              name: secrets-store-creds

---
apiVersion: v1
kind: Service
metadata: 
  name: poi
  namespace: api
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: poi
