# This is a SecretProviderClass example using a service principal to access Key Vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"         # [OPTIONAL] if not provided, will default to "false"
    keyvaultName: "myKV-blah-blah-blah"          # the name of the KeyVault
    cloudName: ""                   # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud 
    objects:  |
      array:
        - |
          objectName: SQL-SERVER
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
          objectAlias: SQL_SERVER     # [OPTIONAL] object alias
        - |
          objectName: SQL-USER
          objectType: secret
          objectVersion: ""
          objectAlias: SQL_USER     # [OPTIONAL] object alias
        - |
          objectName: SQL-PASSWORD
          objectType: secret
          objectVersion: ""
          objectAlias: SQL_PASSWORD     # [OPTIONAL] object alias
        - |
          objectName: SQL-DBNAME
          objectType: secret
          objectVersion: ""
          objectAlias: SQL_DBNAME     # [OPTIONAL] object alias
    tenantId: "871926aa-0cd1-4a7f-aa2c-64060253914f"                 # the tenant ID of the KeyVault