# This is a SecretProviderClass example using user-assigned identity to access Keyvault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: "ee4b4e9f-77b9-4ab2-88f2-8f0d6e19ebd1"   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: "myKV-blah-blah-blah"        # Set to the name of your Azure Key Vault instance
    objects:  |
      array:
        - |
          objectName: SQL-SERVER
          objectType: secret              # object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQL-USER
          objectType: secret
          objectVersion: ""
    tenantId: "871926aa-0cd1-4a7f-aa2c-64060253914f"               # The tenant ID of the Azure Key Vault instance