apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java-deployment
  namespace: api
  labels:
    deploy: user-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
          - name: user-java
            image: registryylw2763.azurecr.io/tripinsights/user-java:latest
            ports:
            - containerPort: 80
            volumeMounts:
                  - name: secrets-store-inline
                    mountPath: "/secrets"
                    readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname"
            nodePublishSecretRef: 
              name: secrets-store-creds

---
apiVersion: v1
kind: Service
metadata: 
  name: user-java-service
  namespace: api
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: user-java

