kind: Namespace
apiVersion: v1
metadata:
  name: ac
  labels:
    name: ac


kind: Namespace
apiVersion: v1
metadata:
  name: api
  labels:
    name: api

kind: Namespace
apiVersion: v1
metadata:
  name: web
  labels:
    name: web
