apiVersion: v1
kind: Pod
metadata:
  name: shell-ac
  namespace: ac
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
  hostNetwork: true
  dnsPolicy: Default




kubectl exec --stdin --tty shell-ac -- /bin/bash